server:
  port:
    8080
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3316/album?useSSL=false&useLegacyDatetimeCode=false&rewriteBatchedStatements=true
    username: album
    password: album
