server:
  port:
    8080
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/debezium-sample?useSSL=false&useLegacyDatetimeCode=false&rewriteBatchedStatements=true
    username: mysqluser
    password: mysqlpw
